version: "3.8"

services:
  backend:
    container_name: backend
    image: backend
    networks:
      - network1
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
    - "8080:8080"

networks:
  network1:
    external: true
    name: mono-persons
