name: frontend

on:
    push:
      branches-ignore:
      - "main"
      tags:
      - "frontend/*"
permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory:
          ./frontend
    env:
      REGISTRY: public.ecr.aws
      IMAGE_NAME: m6q0g2d8/personregistry-frontend
      BACKEND_HOST: http://backend:8080
      VITE_API_URL: https://persons.kristofferchr.dev
    steps:
    - uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        audience: sts.amazonaws.com
        aws-region: us-east-1
        role-to-assume: arn:aws:iam::992382460472:role/github-action
    - name: Login to Amazon ECR Public
      id: login-ecr-public
      uses: aws-actions/amazon-ecr-login@v2
      with:
        registry-type: public
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
    - name: Setup yarn
      run: npm install -g yarn
    - run: yarn install
    - run: yarn run build
    #            - run: npm test

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=match,pattern=frontend-(.*),group=1
          type=ref,event=branch

    - name: Build and push Docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: ./frontend
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          "BACKEND_HOST=${{ env.BACKEND_HOST }}"
